version: '3'
services:
#   mongo:
#     image: mongo:6
#     restart: always
#     ports:
#       - 27017:27017
#     environment:
#       MONGO_INITDB_DATABASE: analytics

#   backend:
#     build:
#       context: .
#       target: backend
#     ports:
#       - 5000:5000
#     environment:
#       - MONGO_URI=mongodb://mongo:27017/analytics
#       - FRONTEND_URL=http://localhost:8080
#     depends_on:
#       - mongo

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 8080:8080
  
    env_file:
      - ./.env